/*
Cashfree Payout APIs

Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.

API version: 2024-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_payout

import (
	"encoding/json"
)

// checks if the CreateTransferResponseBeneficiaryDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTransferResponseBeneficiaryDetails{}

// CreateTransferResponseBeneficiaryDetails It displays the details of the beneficiary.
type CreateTransferResponseBeneficiaryDetails struct {
        // It displays the unique ID to identify the beneficiary to whom you initiated the transfer request.
    BeneficiaryId *string `json:"beneficiary_id,omitempty"`
    BeneficiaryInstrumentDetails *CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails `json:"beneficiary_instrument_details,omitempty"`
}

// NewCreateTransferResponseBeneficiaryDetails instantiates a new CreateTransferResponseBeneficiaryDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTransferResponseBeneficiaryDetails() *CreateTransferResponseBeneficiaryDetails {
this := CreateTransferResponseBeneficiaryDetails{}
return &this
}

// NewCreateTransferResponseBeneficiaryDetailsWithDefaults instantiates a new CreateTransferResponseBeneficiaryDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTransferResponseBeneficiaryDetailsWithDefaults() *CreateTransferResponseBeneficiaryDetails {
this := CreateTransferResponseBeneficiaryDetails{}
return &this
}

        // GetBeneficiaryId returns the BeneficiaryId field value if set, zero value otherwise.
        func (o *CreateTransferResponseBeneficiaryDetails) GetBeneficiaryId() string {
        if o == nil || IsNil(o.BeneficiaryId) {
        var ret string
        return ret
        }
            return *o.BeneficiaryId
        }

        // GetBeneficiaryIdOk returns a tuple with the BeneficiaryId field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateTransferResponseBeneficiaryDetails) GetBeneficiaryIdOk() (*string, bool) {
        if o == nil || IsNil(o.BeneficiaryId) {
            return nil, false
        }
            return o.BeneficiaryId, true
        }

        // HasBeneficiaryId returns a boolean if a field has been set.
        func (o *CreateTransferResponseBeneficiaryDetails) HasBeneficiaryId() bool {
        if o != nil && !IsNil(o.BeneficiaryId) {
        return true
        }

        return false
        }

        // SetBeneficiaryId gets a reference to the given string and assigns it to the BeneficiaryId field.
        func (o *CreateTransferResponseBeneficiaryDetails) SetBeneficiaryId(v string) {
            o.BeneficiaryId = &v
        }

        // GetBeneficiaryInstrumentDetails returns the BeneficiaryInstrumentDetails field value if set, zero value otherwise.
        func (o *CreateTransferResponseBeneficiaryDetails) GetBeneficiaryInstrumentDetails() CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails {
        if o == nil || IsNil(o.BeneficiaryInstrumentDetails) {
        var ret CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails
        return ret
        }
            return *o.BeneficiaryInstrumentDetails
        }

        // GetBeneficiaryInstrumentDetailsOk returns a tuple with the BeneficiaryInstrumentDetails field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateTransferResponseBeneficiaryDetails) GetBeneficiaryInstrumentDetailsOk() (*CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails, bool) {
        if o == nil || IsNil(o.BeneficiaryInstrumentDetails) {
            return nil, false
        }
            return o.BeneficiaryInstrumentDetails, true
        }

        // HasBeneficiaryInstrumentDetails returns a boolean if a field has been set.
        func (o *CreateTransferResponseBeneficiaryDetails) HasBeneficiaryInstrumentDetails() bool {
        if o != nil && !IsNil(o.BeneficiaryInstrumentDetails) {
        return true
        }

        return false
        }

        // SetBeneficiaryInstrumentDetails gets a reference to the given CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails and assigns it to the BeneficiaryInstrumentDetails field.
        func (o *CreateTransferResponseBeneficiaryDetails) SetBeneficiaryInstrumentDetails(v CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails) {
            o.BeneficiaryInstrumentDetails = &v
        }

func (o CreateTransferResponseBeneficiaryDetails) ToMap() (map[string]interface{}, error) {
toSerialize := map[string]interface{}{}
            if !IsNil(o.BeneficiaryId) {
            toSerialize["beneficiary_id"] = o.BeneficiaryId
            }
            if !IsNil(o.BeneficiaryInstrumentDetails) {
            toSerialize["beneficiary_instrument_details"] = o.BeneficiaryInstrumentDetails
            }
return toSerialize, nil
}



