/*
Cashfree Payout APIs

Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.

API version: 2024-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_payout

import (
	"encoding/json"
)

// checks if the CreateBeneficiaryRequestBeneficiaryInstrumentDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBeneficiaryRequestBeneficiaryInstrumentDetails{}

// CreateBeneficiaryRequestBeneficiaryInstrumentDetails Beneficiary instrument details
type CreateBeneficiaryRequestBeneficiaryInstrumentDetails struct {
        // It is the beneficiary bank account number. The value should be between 9 and 18 characters. Alphanumeric characters are allowed. You need to input bank_ifsc if bank_account_number is passed.
    BankAccountNumber *string `json:"bank_account_number,omitempty"`
        // It is the IFSC information of the beneficiary's bank account in the standard IFSC format. The value should be 11 characters. (The first 4 characters should be alphabets, the 5th character should be a 0, and the remaining 6 characters should be numerals.). You need to input bank_account_number if bank_ifsc is passed.
    BankIfsc *string `json:"bank_ifsc,omitempty"`
        // It is the UPI VPA information of the beneficiary. Only valid UPI VPA information is accepted. It can be an Alphanumeric value with only period (.), hyphen (-), underscore ( _ ), and at the rate of (@). Hyphen (-) is accepted only before at the rate of (@).
    Vpa *string `json:"vpa,omitempty"`
}

// NewCreateBeneficiaryRequestBeneficiaryInstrumentDetails instantiates a new CreateBeneficiaryRequestBeneficiaryInstrumentDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBeneficiaryRequestBeneficiaryInstrumentDetails() *CreateBeneficiaryRequestBeneficiaryInstrumentDetails {
this := CreateBeneficiaryRequestBeneficiaryInstrumentDetails{}
return &this
}

// NewCreateBeneficiaryRequestBeneficiaryInstrumentDetailsWithDefaults instantiates a new CreateBeneficiaryRequestBeneficiaryInstrumentDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBeneficiaryRequestBeneficiaryInstrumentDetailsWithDefaults() *CreateBeneficiaryRequestBeneficiaryInstrumentDetails {
this := CreateBeneficiaryRequestBeneficiaryInstrumentDetails{}
return &this
}

        // GetBankAccountNumber returns the BankAccountNumber field value if set, zero value otherwise.
        func (o *CreateBeneficiaryRequestBeneficiaryInstrumentDetails) GetBankAccountNumber() string {
        if o == nil || IsNil(o.BankAccountNumber) {
        var ret string
        return ret
        }
            return *o.BankAccountNumber
        }

        // GetBankAccountNumberOk returns a tuple with the BankAccountNumber field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateBeneficiaryRequestBeneficiaryInstrumentDetails) GetBankAccountNumberOk() (*string, bool) {
        if o == nil || IsNil(o.BankAccountNumber) {
            return nil, false
        }
            return o.BankAccountNumber, true
        }

        // HasBankAccountNumber returns a boolean if a field has been set.
        func (o *CreateBeneficiaryRequestBeneficiaryInstrumentDetails) HasBankAccountNumber() bool {
        if o != nil && !IsNil(o.BankAccountNumber) {
        return true
        }

        return false
        }

        // SetBankAccountNumber gets a reference to the given string and assigns it to the BankAccountNumber field.
        func (o *CreateBeneficiaryRequestBeneficiaryInstrumentDetails) SetBankAccountNumber(v string) {
            o.BankAccountNumber = &v
        }

        // GetBankIfsc returns the BankIfsc field value if set, zero value otherwise.
        func (o *CreateBeneficiaryRequestBeneficiaryInstrumentDetails) GetBankIfsc() string {
        if o == nil || IsNil(o.BankIfsc) {
        var ret string
        return ret
        }
            return *o.BankIfsc
        }

        // GetBankIfscOk returns a tuple with the BankIfsc field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateBeneficiaryRequestBeneficiaryInstrumentDetails) GetBankIfscOk() (*string, bool) {
        if o == nil || IsNil(o.BankIfsc) {
            return nil, false
        }
            return o.BankIfsc, true
        }

        // HasBankIfsc returns a boolean if a field has been set.
        func (o *CreateBeneficiaryRequestBeneficiaryInstrumentDetails) HasBankIfsc() bool {
        if o != nil && !IsNil(o.BankIfsc) {
        return true
        }

        return false
        }

        // SetBankIfsc gets a reference to the given string and assigns it to the BankIfsc field.
        func (o *CreateBeneficiaryRequestBeneficiaryInstrumentDetails) SetBankIfsc(v string) {
            o.BankIfsc = &v
        }

        // GetVpa returns the Vpa field value if set, zero value otherwise.
        func (o *CreateBeneficiaryRequestBeneficiaryInstrumentDetails) GetVpa() string {
        if o == nil || IsNil(o.Vpa) {
        var ret string
        return ret
        }
            return *o.Vpa
        }

        // GetVpaOk returns a tuple with the Vpa field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateBeneficiaryRequestBeneficiaryInstrumentDetails) GetVpaOk() (*string, bool) {
        if o == nil || IsNil(o.Vpa) {
            return nil, false
        }
            return o.Vpa, true
        }

        // HasVpa returns a boolean if a field has been set.
        func (o *CreateBeneficiaryRequestBeneficiaryInstrumentDetails) HasVpa() bool {
        if o != nil && !IsNil(o.Vpa) {
        return true
        }

        return false
        }

        // SetVpa gets a reference to the given string and assigns it to the Vpa field.
        func (o *CreateBeneficiaryRequestBeneficiaryInstrumentDetails) SetVpa(v string) {
            o.Vpa = &v
        }

func (o CreateBeneficiaryRequestBeneficiaryInstrumentDetails) ToMap() (map[string]interface{}, error) {
toSerialize := map[string]interface{}{}
            if !IsNil(o.BankAccountNumber) {
            toSerialize["bank_account_number"] = o.BankAccountNumber
            }
            if !IsNil(o.BankIfsc) {
            toSerialize["bank_ifsc"] = o.BankIfsc
            }
            if !IsNil(o.Vpa) {
            toSerialize["vpa"] = o.Vpa
            }
return toSerialize, nil
}



