/*
Cashfree Payout APIs

Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.

API version: 2024-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_payout

import (
	"encoding/json"
)

// checks if the CreateTransferRequestBeneficiaryDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTransferRequestBeneficiaryDetails{}

// CreateTransferRequestBeneficiaryDetails It should contain the details of the beneficiary who receives the transfer amount.
type CreateTransferRequestBeneficiaryDetails struct {
        // It is the unique ID you created to identify the beneficiary. Alphanumeric characters are allowed.
    BeneficiaryId *string `json:"beneficiary_id,omitempty"`
        // It is the name of the beneficiary. The maximum character limit is 100.  Only alphabets and whitespaces are allowed. It is required if beneficiary_id is not present.
    BeneficiaryName *string `json:"beneficiary_name,omitempty"`
    BeneficiaryInstrumentDetails *CreateTransferRequestBeneficiaryDetailsBeneficiaryInstrumentDetails `json:"beneficiary_instrument_details,omitempty"`
    BeneficiaryContactDetails *CreateTransferRequestBeneficiaryDetailsBeneficiaryContactDetails `json:"beneficiary_contact_details,omitempty"`
}

// NewCreateTransferRequestBeneficiaryDetails instantiates a new CreateTransferRequestBeneficiaryDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTransferRequestBeneficiaryDetails() *CreateTransferRequestBeneficiaryDetails {
this := CreateTransferRequestBeneficiaryDetails{}
return &this
}

// NewCreateTransferRequestBeneficiaryDetailsWithDefaults instantiates a new CreateTransferRequestBeneficiaryDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTransferRequestBeneficiaryDetailsWithDefaults() *CreateTransferRequestBeneficiaryDetails {
this := CreateTransferRequestBeneficiaryDetails{}
return &this
}

        // GetBeneficiaryId returns the BeneficiaryId field value if set, zero value otherwise.
        func (o *CreateTransferRequestBeneficiaryDetails) GetBeneficiaryId() string {
        if o == nil || IsNil(o.BeneficiaryId) {
        var ret string
        return ret
        }
            return *o.BeneficiaryId
        }

        // GetBeneficiaryIdOk returns a tuple with the BeneficiaryId field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateTransferRequestBeneficiaryDetails) GetBeneficiaryIdOk() (*string, bool) {
        if o == nil || IsNil(o.BeneficiaryId) {
            return nil, false
        }
            return o.BeneficiaryId, true
        }

        // HasBeneficiaryId returns a boolean if a field has been set.
        func (o *CreateTransferRequestBeneficiaryDetails) HasBeneficiaryId() bool {
        if o != nil && !IsNil(o.BeneficiaryId) {
        return true
        }

        return false
        }

        // SetBeneficiaryId gets a reference to the given string and assigns it to the BeneficiaryId field.
        func (o *CreateTransferRequestBeneficiaryDetails) SetBeneficiaryId(v string) {
            o.BeneficiaryId = &v
        }

        // GetBeneficiaryName returns the BeneficiaryName field value if set, zero value otherwise.
        func (o *CreateTransferRequestBeneficiaryDetails) GetBeneficiaryName() string {
        if o == nil || IsNil(o.BeneficiaryName) {
        var ret string
        return ret
        }
            return *o.BeneficiaryName
        }

        // GetBeneficiaryNameOk returns a tuple with the BeneficiaryName field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateTransferRequestBeneficiaryDetails) GetBeneficiaryNameOk() (*string, bool) {
        if o == nil || IsNil(o.BeneficiaryName) {
            return nil, false
        }
            return o.BeneficiaryName, true
        }

        // HasBeneficiaryName returns a boolean if a field has been set.
        func (o *CreateTransferRequestBeneficiaryDetails) HasBeneficiaryName() bool {
        if o != nil && !IsNil(o.BeneficiaryName) {
        return true
        }

        return false
        }

        // SetBeneficiaryName gets a reference to the given string and assigns it to the BeneficiaryName field.
        func (o *CreateTransferRequestBeneficiaryDetails) SetBeneficiaryName(v string) {
            o.BeneficiaryName = &v
        }

        // GetBeneficiaryInstrumentDetails returns the BeneficiaryInstrumentDetails field value if set, zero value otherwise.
        func (o *CreateTransferRequestBeneficiaryDetails) GetBeneficiaryInstrumentDetails() CreateTransferRequestBeneficiaryDetailsBeneficiaryInstrumentDetails {
        if o == nil || IsNil(o.BeneficiaryInstrumentDetails) {
        var ret CreateTransferRequestBeneficiaryDetailsBeneficiaryInstrumentDetails
        return ret
        }
            return *o.BeneficiaryInstrumentDetails
        }

        // GetBeneficiaryInstrumentDetailsOk returns a tuple with the BeneficiaryInstrumentDetails field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateTransferRequestBeneficiaryDetails) GetBeneficiaryInstrumentDetailsOk() (*CreateTransferRequestBeneficiaryDetailsBeneficiaryInstrumentDetails, bool) {
        if o == nil || IsNil(o.BeneficiaryInstrumentDetails) {
            return nil, false
        }
            return o.BeneficiaryInstrumentDetails, true
        }

        // HasBeneficiaryInstrumentDetails returns a boolean if a field has been set.
        func (o *CreateTransferRequestBeneficiaryDetails) HasBeneficiaryInstrumentDetails() bool {
        if o != nil && !IsNil(o.BeneficiaryInstrumentDetails) {
        return true
        }

        return false
        }

        // SetBeneficiaryInstrumentDetails gets a reference to the given CreateTransferRequestBeneficiaryDetailsBeneficiaryInstrumentDetails and assigns it to the BeneficiaryInstrumentDetails field.
        func (o *CreateTransferRequestBeneficiaryDetails) SetBeneficiaryInstrumentDetails(v CreateTransferRequestBeneficiaryDetailsBeneficiaryInstrumentDetails) {
            o.BeneficiaryInstrumentDetails = &v
        }

        // GetBeneficiaryContactDetails returns the BeneficiaryContactDetails field value if set, zero value otherwise.
        func (o *CreateTransferRequestBeneficiaryDetails) GetBeneficiaryContactDetails() CreateTransferRequestBeneficiaryDetailsBeneficiaryContactDetails {
        if o == nil || IsNil(o.BeneficiaryContactDetails) {
        var ret CreateTransferRequestBeneficiaryDetailsBeneficiaryContactDetails
        return ret
        }
            return *o.BeneficiaryContactDetails
        }

        // GetBeneficiaryContactDetailsOk returns a tuple with the BeneficiaryContactDetails field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateTransferRequestBeneficiaryDetails) GetBeneficiaryContactDetailsOk() (*CreateTransferRequestBeneficiaryDetailsBeneficiaryContactDetails, bool) {
        if o == nil || IsNil(o.BeneficiaryContactDetails) {
            return nil, false
        }
            return o.BeneficiaryContactDetails, true
        }

        // HasBeneficiaryContactDetails returns a boolean if a field has been set.
        func (o *CreateTransferRequestBeneficiaryDetails) HasBeneficiaryContactDetails() bool {
        if o != nil && !IsNil(o.BeneficiaryContactDetails) {
        return true
        }

        return false
        }

        // SetBeneficiaryContactDetails gets a reference to the given CreateTransferRequestBeneficiaryDetailsBeneficiaryContactDetails and assigns it to the BeneficiaryContactDetails field.
        func (o *CreateTransferRequestBeneficiaryDetails) SetBeneficiaryContactDetails(v CreateTransferRequestBeneficiaryDetailsBeneficiaryContactDetails) {
            o.BeneficiaryContactDetails = &v
        }

    func (o CreateTransferRequestBeneficiaryDetails) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
    return []byte{}, err
    }
    return json.Marshal(toSerialize)
    }

func (o CreateTransferRequestBeneficiaryDetails) ToMap() (map[string]interface{}, error) {
toSerialize := map[string]interface{}{}
            if !IsNil(o.BeneficiaryId) {
            toSerialize["beneficiary_id"] = o.BeneficiaryId
            }
            if !IsNil(o.BeneficiaryName) {
            toSerialize["beneficiary_name"] = o.BeneficiaryName
            }
            if !IsNil(o.BeneficiaryInstrumentDetails) {
            toSerialize["beneficiary_instrument_details"] = o.BeneficiaryInstrumentDetails
            }
            if !IsNil(o.BeneficiaryContactDetails) {
            toSerialize["beneficiary_contact_details"] = o.BeneficiaryContactDetails
            }
return toSerialize, nil
}



