/*
Cashfree Payout APIs

Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.

API version: 2024-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_payout

import (
	"encoding/json"
)

// checks if the FetchBatchTransferResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchBatchTransferResponse{}

// FetchBatchTransferResponse Batch Transfer Status V2 Response
type FetchBatchTransferResponse struct {
        // It displays the unique ID you created to identify the batch transfer.
    BatchTransferId *string `json:"batch_transfer_id,omitempty"`
        // It displays the unique ID created by Cashfree Payments. You receive this ID in the response after initiating the batch transfer request.
    CfBatchTransferId *string `json:"cf_batch_transfer_id,omitempty"`
        // It displays the status of the batch transfer.
    Status *string `json:"status,omitempty"`
    Transfers []CreateTransferResponse `json:"transfers,omitempty"`
}

// NewFetchBatchTransferResponse instantiates a new FetchBatchTransferResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchBatchTransferResponse() *FetchBatchTransferResponse {
this := FetchBatchTransferResponse{}
return &this
}

// NewFetchBatchTransferResponseWithDefaults instantiates a new FetchBatchTransferResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchBatchTransferResponseWithDefaults() *FetchBatchTransferResponse {
this := FetchBatchTransferResponse{}
return &this
}

        // GetBatchTransferId returns the BatchTransferId field value if set, zero value otherwise.
        func (o *FetchBatchTransferResponse) GetBatchTransferId() string {
        if o == nil || IsNil(o.BatchTransferId) {
        var ret string
        return ret
        }
            return *o.BatchTransferId
        }

        // GetBatchTransferIdOk returns a tuple with the BatchTransferId field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *FetchBatchTransferResponse) GetBatchTransferIdOk() (*string, bool) {
        if o == nil || IsNil(o.BatchTransferId) {
            return nil, false
        }
            return o.BatchTransferId, true
        }

        // HasBatchTransferId returns a boolean if a field has been set.
        func (o *FetchBatchTransferResponse) HasBatchTransferId() bool {
        if o != nil && !IsNil(o.BatchTransferId) {
        return true
        }

        return false
        }

        // SetBatchTransferId gets a reference to the given string and assigns it to the BatchTransferId field.
        func (o *FetchBatchTransferResponse) SetBatchTransferId(v string) {
            o.BatchTransferId = &v
        }

        // GetCfBatchTransferId returns the CfBatchTransferId field value if set, zero value otherwise.
        func (o *FetchBatchTransferResponse) GetCfBatchTransferId() string {
        if o == nil || IsNil(o.CfBatchTransferId) {
        var ret string
        return ret
        }
            return *o.CfBatchTransferId
        }

        // GetCfBatchTransferIdOk returns a tuple with the CfBatchTransferId field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *FetchBatchTransferResponse) GetCfBatchTransferIdOk() (*string, bool) {
        if o == nil || IsNil(o.CfBatchTransferId) {
            return nil, false
        }
            return o.CfBatchTransferId, true
        }

        // HasCfBatchTransferId returns a boolean if a field has been set.
        func (o *FetchBatchTransferResponse) HasCfBatchTransferId() bool {
        if o != nil && !IsNil(o.CfBatchTransferId) {
        return true
        }

        return false
        }

        // SetCfBatchTransferId gets a reference to the given string and assigns it to the CfBatchTransferId field.
        func (o *FetchBatchTransferResponse) SetCfBatchTransferId(v string) {
            o.CfBatchTransferId = &v
        }

        // GetStatus returns the Status field value if set, zero value otherwise.
        func (o *FetchBatchTransferResponse) GetStatus() string {
        if o == nil || IsNil(o.Status) {
        var ret string
        return ret
        }
            return *o.Status
        }

        // GetStatusOk returns a tuple with the Status field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *FetchBatchTransferResponse) GetStatusOk() (*string, bool) {
        if o == nil || IsNil(o.Status) {
            return nil, false
        }
            return o.Status, true
        }

        // HasStatus returns a boolean if a field has been set.
        func (o *FetchBatchTransferResponse) HasStatus() bool {
        if o != nil && !IsNil(o.Status) {
        return true
        }

        return false
        }

        // SetStatus gets a reference to the given string and assigns it to the Status field.
        func (o *FetchBatchTransferResponse) SetStatus(v string) {
            o.Status = &v
        }

        // GetTransfers returns the Transfers field value if set, zero value otherwise.
        func (o *FetchBatchTransferResponse) GetTransfers() []CreateTransferResponse {
        if o == nil || IsNil(o.Transfers) {
        var ret []CreateTransferResponse
        return ret
        }
            return o.Transfers
        }

        // GetTransfersOk returns a tuple with the Transfers field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *FetchBatchTransferResponse) GetTransfersOk() ([]CreateTransferResponse, bool) {
        if o == nil || IsNil(o.Transfers) {
            return nil, false
        }
            return o.Transfers, true
        }

        // HasTransfers returns a boolean if a field has been set.
        func (o *FetchBatchTransferResponse) HasTransfers() bool {
        if o != nil && !IsNil(o.Transfers) {
        return true
        }

        return false
        }

        // SetTransfers gets a reference to the given []CreateTransferResponse and assigns it to the Transfers field.
        func (o *FetchBatchTransferResponse) SetTransfers(v []CreateTransferResponse) {
            o.Transfers = v
        }

func (o FetchBatchTransferResponse) ToMap() (map[string]interface{}, error) {
toSerialize := map[string]interface{}{}
            if !IsNil(o.BatchTransferId) {
            toSerialize["batch_transfer_id"] = o.BatchTransferId
            }
            if !IsNil(o.CfBatchTransferId) {
            toSerialize["cf_batch_transfer_id"] = o.CfBatchTransferId
            }
            if !IsNil(o.Status) {
            toSerialize["status"] = o.Status
            }
            if !IsNil(o.Transfers) {
            toSerialize["transfers"] = o.Transfers
            }
return toSerialize, nil
}



