/*
Cashfree Payout APIs

Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.

API version: 2024-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_payout

import (
	"encoding/json"
)

// checks if the CreateBatchTransferRequestTransfersInnerBeneficiaryDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBatchTransferRequestTransfersInnerBeneficiaryDetails{}

// CreateBatchTransferRequestTransfersInnerBeneficiaryDetails It should contain the details of the beneficiary who receives the transfer amount.
type CreateBatchTransferRequestTransfersInnerBeneficiaryDetails struct {
        // It is the unique ID you created to identify the beneficiary. Alphanumeric characters are allowed.
    BeneficiaryId *string `json:"beneficiary_id,omitempty"`
        // It is the name of the beneficiary. The maximum character limit is 100.
    BeneficiaryName *string `json:"beneficiary_name,omitempty"`
    BeneficiaryInstrumentDetails *CreateBatchTransferRequestTransfersInnerBeneficiaryDetailsBeneficiaryInstrumentDetails `json:"beneficiary_instrument_details,omitempty"`
    BeneficiaryContactDetails *CreateTransferRequestBeneficiaryDetailsBeneficiaryContactDetails `json:"beneficiary_contact_details,omitempty"`
}

// NewCreateBatchTransferRequestTransfersInnerBeneficiaryDetails instantiates a new CreateBatchTransferRequestTransfersInnerBeneficiaryDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBatchTransferRequestTransfersInnerBeneficiaryDetails() *CreateBatchTransferRequestTransfersInnerBeneficiaryDetails {
this := CreateBatchTransferRequestTransfersInnerBeneficiaryDetails{}
return &this
}

// NewCreateBatchTransferRequestTransfersInnerBeneficiaryDetailsWithDefaults instantiates a new CreateBatchTransferRequestTransfersInnerBeneficiaryDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBatchTransferRequestTransfersInnerBeneficiaryDetailsWithDefaults() *CreateBatchTransferRequestTransfersInnerBeneficiaryDetails {
this := CreateBatchTransferRequestTransfersInnerBeneficiaryDetails{}
return &this
}

        // GetBeneficiaryId returns the BeneficiaryId field value if set, zero value otherwise.
        func (o *CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) GetBeneficiaryId() string {
        if o == nil || IsNil(o.BeneficiaryId) {
        var ret string
        return ret
        }
            return *o.BeneficiaryId
        }

        // GetBeneficiaryIdOk returns a tuple with the BeneficiaryId field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) GetBeneficiaryIdOk() (*string, bool) {
        if o == nil || IsNil(o.BeneficiaryId) {
            return nil, false
        }
            return o.BeneficiaryId, true
        }

        // HasBeneficiaryId returns a boolean if a field has been set.
        func (o *CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) HasBeneficiaryId() bool {
        if o != nil && !IsNil(o.BeneficiaryId) {
        return true
        }

        return false
        }

        // SetBeneficiaryId gets a reference to the given string and assigns it to the BeneficiaryId field.
        func (o *CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) SetBeneficiaryId(v string) {
            o.BeneficiaryId = &v
        }

        // GetBeneficiaryName returns the BeneficiaryName field value if set, zero value otherwise.
        func (o *CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) GetBeneficiaryName() string {
        if o == nil || IsNil(o.BeneficiaryName) {
        var ret string
        return ret
        }
            return *o.BeneficiaryName
        }

        // GetBeneficiaryNameOk returns a tuple with the BeneficiaryName field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) GetBeneficiaryNameOk() (*string, bool) {
        if o == nil || IsNil(o.BeneficiaryName) {
            return nil, false
        }
            return o.BeneficiaryName, true
        }

        // HasBeneficiaryName returns a boolean if a field has been set.
        func (o *CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) HasBeneficiaryName() bool {
        if o != nil && !IsNil(o.BeneficiaryName) {
        return true
        }

        return false
        }

        // SetBeneficiaryName gets a reference to the given string and assigns it to the BeneficiaryName field.
        func (o *CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) SetBeneficiaryName(v string) {
            o.BeneficiaryName = &v
        }

        // GetBeneficiaryInstrumentDetails returns the BeneficiaryInstrumentDetails field value if set, zero value otherwise.
        func (o *CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) GetBeneficiaryInstrumentDetails() CreateBatchTransferRequestTransfersInnerBeneficiaryDetailsBeneficiaryInstrumentDetails {
        if o == nil || IsNil(o.BeneficiaryInstrumentDetails) {
        var ret CreateBatchTransferRequestTransfersInnerBeneficiaryDetailsBeneficiaryInstrumentDetails
        return ret
        }
            return *o.BeneficiaryInstrumentDetails
        }

        // GetBeneficiaryInstrumentDetailsOk returns a tuple with the BeneficiaryInstrumentDetails field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) GetBeneficiaryInstrumentDetailsOk() (*CreateBatchTransferRequestTransfersInnerBeneficiaryDetailsBeneficiaryInstrumentDetails, bool) {
        if o == nil || IsNil(o.BeneficiaryInstrumentDetails) {
            return nil, false
        }
            return o.BeneficiaryInstrumentDetails, true
        }

        // HasBeneficiaryInstrumentDetails returns a boolean if a field has been set.
        func (o *CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) HasBeneficiaryInstrumentDetails() bool {
        if o != nil && !IsNil(o.BeneficiaryInstrumentDetails) {
        return true
        }

        return false
        }

        // SetBeneficiaryInstrumentDetails gets a reference to the given CreateBatchTransferRequestTransfersInnerBeneficiaryDetailsBeneficiaryInstrumentDetails and assigns it to the BeneficiaryInstrumentDetails field.
        func (o *CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) SetBeneficiaryInstrumentDetails(v CreateBatchTransferRequestTransfersInnerBeneficiaryDetailsBeneficiaryInstrumentDetails) {
            o.BeneficiaryInstrumentDetails = &v
        }

        // GetBeneficiaryContactDetails returns the BeneficiaryContactDetails field value if set, zero value otherwise.
        func (o *CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) GetBeneficiaryContactDetails() CreateTransferRequestBeneficiaryDetailsBeneficiaryContactDetails {
        if o == nil || IsNil(o.BeneficiaryContactDetails) {
        var ret CreateTransferRequestBeneficiaryDetailsBeneficiaryContactDetails
        return ret
        }
            return *o.BeneficiaryContactDetails
        }

        // GetBeneficiaryContactDetailsOk returns a tuple with the BeneficiaryContactDetails field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) GetBeneficiaryContactDetailsOk() (*CreateTransferRequestBeneficiaryDetailsBeneficiaryContactDetails, bool) {
        if o == nil || IsNil(o.BeneficiaryContactDetails) {
            return nil, false
        }
            return o.BeneficiaryContactDetails, true
        }

        // HasBeneficiaryContactDetails returns a boolean if a field has been set.
        func (o *CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) HasBeneficiaryContactDetails() bool {
        if o != nil && !IsNil(o.BeneficiaryContactDetails) {
        return true
        }

        return false
        }

        // SetBeneficiaryContactDetails gets a reference to the given CreateTransferRequestBeneficiaryDetailsBeneficiaryContactDetails and assigns it to the BeneficiaryContactDetails field.
        func (o *CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) SetBeneficiaryContactDetails(v CreateTransferRequestBeneficiaryDetailsBeneficiaryContactDetails) {
            o.BeneficiaryContactDetails = &v
        }

func (o CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) ToMap() (map[string]interface{}, error) {
toSerialize := map[string]interface{}{}
            if !IsNil(o.BeneficiaryId) {
            toSerialize["beneficiary_id"] = o.BeneficiaryId
            }
            if !IsNil(o.BeneficiaryName) {
            toSerialize["beneficiary_name"] = o.BeneficiaryName
            }
            if !IsNil(o.BeneficiaryInstrumentDetails) {
            toSerialize["beneficiary_instrument_details"] = o.BeneficiaryInstrumentDetails
            }
            if !IsNil(o.BeneficiaryContactDetails) {
            toSerialize["beneficiary_contact_details"] = o.BeneficiaryContactDetails
            }
return toSerialize, nil
}



