/*
Cashfree Payout APIs

Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.

API version: 2024-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_payout

import (
	"encoding/json"
)

// checks if the CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails{}

// CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails It displays the details of where the beneficiary will receive the money.
type CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails struct {
        // It displays the bank account number of the beneficiary.
    BankAccountNumber *string `json:"bank_account_number,omitempty"`
        // It displays the IFSC information of the beneficiary's bank account.
    Ifsc *string `json:"ifsc,omitempty"`
        // It displays the UPI VPA information of the beneficiary.
    Vpa *string `json:"vpa,omitempty"`
}

// NewCreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails instantiates a new CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails() *CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails {
this := CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails{}
return &this
}

// NewCreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetailsWithDefaults instantiates a new CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetailsWithDefaults() *CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails {
this := CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails{}
return &this
}

        // GetBankAccountNumber returns the BankAccountNumber field value if set, zero value otherwise.
        func (o *CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails) GetBankAccountNumber() string {
        if o == nil || IsNil(o.BankAccountNumber) {
        var ret string
        return ret
        }
            return *o.BankAccountNumber
        }

        // GetBankAccountNumberOk returns a tuple with the BankAccountNumber field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails) GetBankAccountNumberOk() (*string, bool) {
        if o == nil || IsNil(o.BankAccountNumber) {
            return nil, false
        }
            return o.BankAccountNumber, true
        }

        // HasBankAccountNumber returns a boolean if a field has been set.
        func (o *CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails) HasBankAccountNumber() bool {
        if o != nil && !IsNil(o.BankAccountNumber) {
        return true
        }

        return false
        }

        // SetBankAccountNumber gets a reference to the given string and assigns it to the BankAccountNumber field.
        func (o *CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails) SetBankAccountNumber(v string) {
            o.BankAccountNumber = &v
        }

        // GetIfsc returns the Ifsc field value if set, zero value otherwise.
        func (o *CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails) GetIfsc() string {
        if o == nil || IsNil(o.Ifsc) {
        var ret string
        return ret
        }
            return *o.Ifsc
        }

        // GetIfscOk returns a tuple with the Ifsc field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails) GetIfscOk() (*string, bool) {
        if o == nil || IsNil(o.Ifsc) {
            return nil, false
        }
            return o.Ifsc, true
        }

        // HasIfsc returns a boolean if a field has been set.
        func (o *CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails) HasIfsc() bool {
        if o != nil && !IsNil(o.Ifsc) {
        return true
        }

        return false
        }

        // SetIfsc gets a reference to the given string and assigns it to the Ifsc field.
        func (o *CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails) SetIfsc(v string) {
            o.Ifsc = &v
        }

        // GetVpa returns the Vpa field value if set, zero value otherwise.
        func (o *CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails) GetVpa() string {
        if o == nil || IsNil(o.Vpa) {
        var ret string
        return ret
        }
            return *o.Vpa
        }

        // GetVpaOk returns a tuple with the Vpa field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails) GetVpaOk() (*string, bool) {
        if o == nil || IsNil(o.Vpa) {
            return nil, false
        }
            return o.Vpa, true
        }

        // HasVpa returns a boolean if a field has been set.
        func (o *CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails) HasVpa() bool {
        if o != nil && !IsNil(o.Vpa) {
        return true
        }

        return false
        }

        // SetVpa gets a reference to the given string and assigns it to the Vpa field.
        func (o *CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails) SetVpa(v string) {
            o.Vpa = &v
        }

    func (o CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
    return []byte{}, err
    }
    return json.Marshal(toSerialize)
    }

func (o CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails) ToMap() (map[string]interface{}, error) {
toSerialize := map[string]interface{}{}
            if !IsNil(o.BankAccountNumber) {
            toSerialize["bank_account_number"] = o.BankAccountNumber
            }
            if !IsNil(o.Ifsc) {
            toSerialize["ifsc"] = o.Ifsc
            }
            if !IsNil(o.Vpa) {
            toSerialize["vpa"] = o.Vpa
            }
return toSerialize, nil
}



