/*
Cashfree Payout APIs

Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.

API version: 2024-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_payout

import (
	"encoding/json"
)

// checks if the CreateBatchTransferResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBatchTransferResponse{}

// CreateBatchTransferResponse Batch Transfer V2 Response
type CreateBatchTransferResponse struct {
        // It displays the unique ID you created to identify the batch transfer request.
    BatchTransferId *string `json:"batch_transfer_id,omitempty"`
        // It displays the unique ID created by Cashfree Payments. You receive this ID in the response after initiating the batch transfer request.
    CfBatchTransferId *string `json:"cf_batch_transfer_id,omitempty"`
        // It displays the status of the API request.
    Status *string `json:"status,omitempty"`
}

// NewCreateBatchTransferResponse instantiates a new CreateBatchTransferResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBatchTransferResponse() *CreateBatchTransferResponse {
this := CreateBatchTransferResponse{}
return &this
}

// NewCreateBatchTransferResponseWithDefaults instantiates a new CreateBatchTransferResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBatchTransferResponseWithDefaults() *CreateBatchTransferResponse {
this := CreateBatchTransferResponse{}
return &this
}

        // GetBatchTransferId returns the BatchTransferId field value if set, zero value otherwise.
        func (o *CreateBatchTransferResponse) GetBatchTransferId() string {
        if o == nil || IsNil(o.BatchTransferId) {
        var ret string
        return ret
        }
            return *o.BatchTransferId
        }

        // GetBatchTransferIdOk returns a tuple with the BatchTransferId field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateBatchTransferResponse) GetBatchTransferIdOk() (*string, bool) {
        if o == nil || IsNil(o.BatchTransferId) {
            return nil, false
        }
            return o.BatchTransferId, true
        }

        // HasBatchTransferId returns a boolean if a field has been set.
        func (o *CreateBatchTransferResponse) HasBatchTransferId() bool {
        if o != nil && !IsNil(o.BatchTransferId) {
        return true
        }

        return false
        }

        // SetBatchTransferId gets a reference to the given string and assigns it to the BatchTransferId field.
        func (o *CreateBatchTransferResponse) SetBatchTransferId(v string) {
            o.BatchTransferId = &v
        }

        // GetCfBatchTransferId returns the CfBatchTransferId field value if set, zero value otherwise.
        func (o *CreateBatchTransferResponse) GetCfBatchTransferId() string {
        if o == nil || IsNil(o.CfBatchTransferId) {
        var ret string
        return ret
        }
            return *o.CfBatchTransferId
        }

        // GetCfBatchTransferIdOk returns a tuple with the CfBatchTransferId field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateBatchTransferResponse) GetCfBatchTransferIdOk() (*string, bool) {
        if o == nil || IsNil(o.CfBatchTransferId) {
            return nil, false
        }
            return o.CfBatchTransferId, true
        }

        // HasCfBatchTransferId returns a boolean if a field has been set.
        func (o *CreateBatchTransferResponse) HasCfBatchTransferId() bool {
        if o != nil && !IsNil(o.CfBatchTransferId) {
        return true
        }

        return false
        }

        // SetCfBatchTransferId gets a reference to the given string and assigns it to the CfBatchTransferId field.
        func (o *CreateBatchTransferResponse) SetCfBatchTransferId(v string) {
            o.CfBatchTransferId = &v
        }

        // GetStatus returns the Status field value if set, zero value otherwise.
        func (o *CreateBatchTransferResponse) GetStatus() string {
        if o == nil || IsNil(o.Status) {
        var ret string
        return ret
        }
            return *o.Status
        }

        // GetStatusOk returns a tuple with the Status field value if set, nil otherwise
        // and a boolean to check if the value has been set.
        func (o *CreateBatchTransferResponse) GetStatusOk() (*string, bool) {
        if o == nil || IsNil(o.Status) {
            return nil, false
        }
            return o.Status, true
        }

        // HasStatus returns a boolean if a field has been set.
        func (o *CreateBatchTransferResponse) HasStatus() bool {
        if o != nil && !IsNil(o.Status) {
        return true
        }

        return false
        }

        // SetStatus gets a reference to the given string and assigns it to the Status field.
        func (o *CreateBatchTransferResponse) SetStatus(v string) {
            o.Status = &v
        }

    func (o CreateBatchTransferResponse) MarshalJSON() ([]byte, error) {
    toSerialize,err := o.ToMap()
    if err != nil {
    return []byte{}, err
    }
    return json.Marshal(toSerialize)
    }

func (o CreateBatchTransferResponse) ToMap() (map[string]interface{}, error) {
toSerialize := map[string]interface{}{}
            if !IsNil(o.BatchTransferId) {
            toSerialize["batch_transfer_id"] = o.BatchTransferId
            }
            if !IsNil(o.CfBatchTransferId) {
            toSerialize["cf_batch_transfer_id"] = o.CfBatchTransferId
            }
            if !IsNil(o.Status) {
            toSerialize["status"] = o.Status
            }
return toSerialize, nil
}



